services:
  postgres:
    image: "postgres:16-alpine"
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  strapi:
    image: strapi/strapi
    restart: unless-stopped
    volumes:
      - ./strapi:/srv/app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  web:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - strapi

volumes:
  postgres-data:
