services:
  postgres:
    image: "postgres:16-alpine"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: strapi
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  strapi:
    image: strapi/strapi
    restart: always
    volumes:
      - ./strapi:/srv/app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  web:
    build: .
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - strapi

volumes:
  postgres-data:
