services:
  postgres:
    image: "postgres:16-alpine"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  strapi:
    image: ghcr.io/sehrgutesoftware/strapi-dockerized/dev:latest
    restart: always
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ${PWD}/strapi/src:/app/src
      - ${PWD}/strapi/config:/app/config
      - ./uploads:/app/public/uploads
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  web:
    build: .
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - strapi

volumes:
  postgres-data:
